version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.9
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            echo $(circleci tests glob "tests/*")
            circleci tests glob "tests/*" | xargs -n 1 echo
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest -v tests/
      - store_test_results:
          path: test-results